### ISSUE TITLE
Price fields in database keep showing as updated

### ISSUE THREAD

**Issue by aderuwe** [TheBigBrainsCompany/TbbcMoneyBundle#55] opened 2016-02-24 10:28 UTC
```
$ app/console doctrine:schema:update --dump-sql
ALTER TABLE order_items CHANGE price price VARCHAR(255) NOT NULL;
ALTER TABLE products CHANGE price price VARCHAR(255) NOT NULL;
ALTER TABLE product_variants CHANGE price price VARCHAR(255) NOT NULL;

$ app/console doctrine:schema:update --force
Updating database schema...
Database schema updated successfully! "3" queries were executed

$ app/console doctrine:schema:update --dump-sql
ALTER TABLE order_items CHANGE price price VARCHAR(255) NOT NULL;
ALTER TABLE products CHANGE price price VARCHAR(255) NOT NULL;
ALTER TABLE product_variants CHANGE price price VARCHAR(255) NOT NULL;
```

Any way to avoid this?

**Comment by geekdevs** [comment] 2016-02-27 18:01
@aderuwe I guess you're using `money` type for storing values? A bit off topic, but I would recommend using 2 fields instead (https://github.com/TheBigBrainsCompany/TbbcMoneyBundle#solution-1--two-fields-in-the-database). In my opinion this is much more flexible solution as it allows you to easily index and search for values.

**Comment by maercky** [comment] 2016-06-16 21:49
Is there an update on this? 😃

**Comment by mhlavac** [comment] 2016-07-25 08:55
@aderuwe @maercky for us this got solved when we added comment to database column

in postgres:
```
COMMENT ON COLUMN product.purchase_price IS '(DC2Type:money)';
```

**Comment by mrcmorales** [comment] 2016-10-05 10:19
hi @aderuwe,

You need to add this option in doctrine configuration:

```doctrine:
    dbal:
        mapping_types:
          money: string```

**Comment by aderuwe** [comment] 2016-10-05 10:33
@mrcmorales unfortunately, that doesn't seem to do anything here.

**Comment by mrcmorales** [comment] 2016-10-05 10:49
@aderuwe sorry, I updated my comment, trye now.

**Comment by geekdevs** [comment] 2016-10-12 16:13
@aderuwe does this solve it for you?

**Comment by aderuwe** [comment] 2016-10-12 16:42
It did not. I should probably try with latest versions of things, tho...

**Comment by mrcmorales** [comment] 2016-10-13 15:37
@aderuwe @geekdevs for me is working great this and for different projects, I'm using it with doctrine migrations.

**Comment by geekdevs** [comment] 2016-10-17 17:11
I cannot reproduce the issue on the latest master. I assume this is doctrine version related.
@aderuwe  Please share your package versions (so that I could add a note about that to README) by running the following:

`composer info | grep "symfony/symfony\|doctrine\|tbbc"`

and

`php -v`

**Comment by geekdevs** [comment] 2016-11-10 08:21
closing as no further feedback provided. Feel free to re-open with more info if error still occurs.

**Closed by geekdevs** 2016-11-10 08:21 UTC
Labels: bug
